### ISSUE TITLE
Quick question on the settings

### ISSUE THREAD

**Issue by Z1839** [lovac42/HoochieMama#12]
Hey man, this isn't an issue but I needed some help with settings when using Hoochie Baby, mama, and papa. I'm still learning the vocab for anki so I apologize if this is an easy question.

I was wondering what settings I should use with all three so that I can study new cards but want more of my reviews to show up relative to news.

Should I use "Prioritize Today" with sort by "Dues" or "Overdues" on both Mama and Baby for this? 

again, thanks for everything!

**Comment by lovac42** [comment]
Prioritize today should be used sparingly when you have alot of overdues. I don't know of your situation, but randomizing everything is the better option for reviews. Just like in the real world, ideas and information pops up randomly, if you are the speaker asked to address those questions, randomized reviews would be more realistic. So set "Shuffle" on mama and sort by "Overdues" for baby and papa would be easier for learning.

**Comment by Z1839** [comment]
Really good stuff my man, I was using prioritize today because I thought it would bring more reviews into my shuffles. I disabled it now.

I too agree that randomizing everything is better because ideas and info pop up randomly in the real world. It couldn't have been said any better.

So setting "Shuffle" on mama and sort by "Overdues" for baby and "Dues (asc)" for papa would be easier for learning would make more of my reviews pop up relative to news cards?

**Comment by lovac42** [comment]
>would make more of my reviews pop up relative to news cards?
If you do not use QController, that is set by Anki. These addons do not control those.

Not using subdeck limit for mama is better, that is from V2. Using subdeck limit is better if you have alot of hard subjects mixed together and haven't fully transitioned. Instead of getting 50 math cards, each subdeck will be limited. Then you can turn it off once all of your subdecks are studied and evenly distributed across multiple days.
